/** @format */

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getLegalMoves } from "../../lib/legalMoves";
import { useEffect, useState } from "react";
import {
  getMyAccount,
  RequestChallenge,
  getListOfBots,
  getMyGames,
  streamOfGameEvents,
  makeAMove,
  streamOfSpecificGame,
} from "../../lib/games";
import { Challenge } from "../../types";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [activeGames, setActiveGames] = useState<any>([]);
  interface nowPlaying {
    nowPlaying: {
      id: string;
      fen: string;
    };
  }
  function evaluatePosition() {
    const firstGame = activeGames["nowPlaying"][0];
    const legalMoves = getLegalMoves(firstGame.fen)["legalMoves"];
    let move = "";

    function getMove() {
      const numberFrom0To15 = Math.floor(Math.random() * 16);
      if (legalMoves[numberFrom0To15].from.length > 0) {
        if (legalMoves[numberFrom0To15].quietMoves.length > 0) {
          move =
            legalMoves[numberFrom0To15].from +
            legalMoves[numberFrom0To15].quietMoves[0];
        }
        if (legalMoves[numberFrom0To15].killMoves.length > 0) {
          move =
            legalMoves[numberFrom0To15].from +
            legalMoves[numberFrom0To15].killMoves[0];
        }
      }
    }

    while (move.length === 0) {
      getMove();
    }
    makeAMove(firstGame.fullId, move).then((res) => {
      setTimeout(() => {
        getMyGames().then((games) => {
          setActiveGames(games);
          console.log(games);
        });
      }, 1000);
    });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            gap: "1em",
          }}
        >
          <button
            style={{
              backgroundColor: "red",
              color: "white",
              padding: "10px",
              borderRadius: "5px",
              marginLeft: "10px",
            }}
            onClick={() => {
              RequestChallenge();
            }}
          >
            request challenge
          </button>
          <button onClick={getMyAccount}>Get My Account</button>
          <button onClick={getListOfBots}>Get List of Bots</button>
          <button onClick={streamOfGameEvents}>Stream of game events</button>
          <button onClick={() => makeAMove("cgkfTWHS", "e2e4")}>
            make a move
          </button>
          <button
            onClick={() => {
              getMyGames().then((games) => {
                setActiveGames(games);
                console.log(games);
              });
            }}
          >
            Get My Active Games
          </button>
          <button
            onClick={() => {
              evaluatePosition();
            }}
          >
            Get Legal Moves
          </button>
          <button onClick={() => streamOfSpecificGame("cgkfTWHS")}>
            stream of specific game
          </button>
        </div>
      </main>
    </>
  );
}
